### ISSUE TITLE
PHP dependencies

### ISSUE THREAD

**Issue by mourawaldson** [pbougie/mac-dev-env#11]
The way that ./configure was setup for https://github.com/pbougie/mac-dev-env/blob/master/source/php.html.markdown is missing the PostgreSQL.
I didn't a pull request because I don't know if you prefer to mention as optional and show the config option that could be used or just add to dependencies list.

**Comment by pbougie** [comment]
The `configure` options are included. See these lines:
```
  --with-pdo-pgsql=/usr/local/postgresql \
  --with-pgsql=/usr/local/postgresql \
```

**Comment by mourawaldson** [comment]
I was trying to say that if PostgreSQL is not listed as a dependency here:
![screen shot 2015-11-09 at 10 24 09 pm](https://cloud.githubusercontent.com/assets/612061/11053668/fc1c4d46-8730-11e5-8bcb-bfaf81bca9f4.png)

We get the following error:
```
checking for PostgreSQL support for PDO... yes
checking for pg_config... not found
configure: error: Cannot find libpq-fe.h. Please specify correct PostgreSQL installation path
```
And happens exactly because of the configuration you've mentioned.

But I don't know if you prefer just add the PostgreSQL as a dependency on the PHP page or move the following code:
```
--with-pdo-pgsql=/usr/local/postgresql \
  --with-pgsql=/usr/local/postgresql \
```
from the current configuration parameters and put a note there on the page saying that these are the options in order to use PostgreSQL.

Just saying because the way it is, I was trying to add each dependency before try to execute the php configuration, and I got the error as I've mentioned above.

**Comment by pbougie** [comment]
I understand now. You are correct. I've added the PostgreSQL dependency at the top. I also added OpenSSL.

**Comment by mourawaldson** [comment]
Nice!
