### ISSUE TITLE
apr and apr-util required for Apache 2.4.20

### ISSUE THREAD

**Issue by lukejanicke** [pbougie/mac-dev-env#18]
I couldn't configure Apache 2.4.20 (latest) without downloading and adding `apr` and `apr-util` to the source.

	cd /usr/local/src/httpd-2.4.20/srclib
	curl --remote-name http://archive.apache.org/dist/apr/apr-1.5.2.tar.gz
	curl --remote-name http://archive.apache.org/dist/apr/apr-util-1.5.4.tar.gz
	tar -xzvf apr-1.5.2.tar.gz
	tar -xzvf apr-util-1.5.4.tar.gz
	mkdir apr
	mkdir apr-util
	mv apr-1.5.2/ apr
	mv apr-util-1.5.4/ apr-util
	cd ..

Then I could compile Apache with the `--with-included-apr` flag.

	./configure --prefix=/usr/local/apache-2.4.20 --with-included-apr

**Comment by pbougie** [comment]
Seems there is a problem with your system. I just compiled Apache v2.4.20 and did not require `apr` as it comes with the system. See `/usr/bin/apr-1-config`.
