### ISSUE TITLE
Safe to turn off system apache?

### ISSUE THREAD

**Issue by preflight** [pbougie/mac-dev-env#19]
Thank you for this guide; I've found it incredibly helpful.

In the Apache guide, could you confirm that the second line below is correct -- that we're really deregistering the same `plist` file we previously registered with Launchd?

```
sudo launchctl load /Library/LaunchDaemons/org.apache.apache2.plist
```
```
sudo launchctl unload /Library/LaunchDaemons/org.apache.apache2.plist
```

When I try to start the server, I am seeing a message that appears to say Port 80 is occupied:
```
MBP:~ Home$ sudo apachectl start
(48)Address already in use: AH00072: make_sock: could not bind to address [::]:80
(48)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
```

Logic tells me to disable the system apache from starting up by doing this:
```
sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist
```

But I'm hesitant since you specifically advise avoiding collision with `org.apache.httpd.plist`.

Is it generally safe to turn off system Apache, or do you advise keeping both versions running?

Thanks again.

**Comment by pbougie** [comment]
Sounds like you’re already using port 80. Presumably the built-in web server is running (this is not the case by default on a new system). I can’t see how it would negatively affect your system to run:

sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist

You can only run both web servers at the same time if they are configured for different ports. You cannot have them both running on port 80.

Hope this helps.

**Comment by preflight** [comment]
Thanks very much for responding. I did go ahead and unload the system apache and that solved the problem. I'm not seeing any related issues - your guide worked like a charm.
