### ISSUE TITLE
mysql install problems, and my resolution

### ISSUE THREAD

**Issue by frumbert** [pbougie/mac-dev-env#20]
In `http://mac-dev-env.patrickbougie.com/mysql/`, I got to the part

    mysql -u root -p

i got this old gem: `ERROR 2002 (HY000): Can't connect to local MySQL server through socket /tmp/mysql.sock`

I had to start the server using mysqld_safe, attempt a connection using another app (Sequel Pro) then attempt `mysql -u root -p` again. This resolved the socket issue. Why? No idea, but it works now.

I also appended these steps https://gist.github.com/larrybotha/288f5e1c5b51fe1bba980f25985b56f8 to avoid the `mysql has gone away` error I've sometimes seen, we well as creating an `/etc/my.cnf' file and dropping in proper utf8mb4 support to avoid unicode problems (some of my apps generally require it, and the utf8 in mysql isn't great, documented https://mathiasbynens.be/notes/mysql-utf8mb4).

Be great to add some of these as notes or optional installation steps to the guide!

**Comment by pbougie** [comment]
@frumbert Thanks for sharing. Your socket problem is most likely a local problem. I've never had issues with the other items so I don't think they need to be added to the guide (I want to keep them as simple as possible) but if others encounter the same issues they can find a solution in this thread. If you want to expand on your solutions, please do so in the thread so the solutions are easily searched.

**Comment by frumbert** [comment]
I had reason to totally uninstall the mysql again afterwards and recompile. I hit the same issue with the socket at the same spot. This was on a fresh install of Sierra (which I did yesterday). I performed my same steps to get past it and it hasn't happened since. But I wasn't able to pick up any reason why it happened, so I'm happy to ignore it.
