### ISSUE TITLE
php failing with linker command failed

### ISSUE THREAD

**Issue by frumbert** [pbougie/mac-dev-env#6]
Thanks for this guide, it was exactly what I needed. I've compiled pretty much everything except php, which is finally outputting `make: *** [libs/libphp5.bundle] Error 1`

Here's the paste from the last cc on to the end

http://pastebin.com/pmydXdzy

Up until this point everything has compiled perfectly.

OSX 10.10.3 (14D2134)

**Comment by pbougie** [comment]
I’ve had similar problems with recent versions of PHP/PostgreSQL. Unfortunately, you have to exclude PostgreSQL support from PHP. To exclude PostgreSQL, remove these options when configuring PHP:
  --with-pdo-pgsql=/usr/local/postgresql \
  --with-pgsql=/usr/local/postgresql \
If you find a better solution, please let me know.

Patrick

**Comment by frumbert** [comment]
Cool. I only included postgres because I was going to fiddle with it, luckily I don't technically need it right now, so hopefully a new release will fix it. Cheers for the reply!
